import type { Rule } from '@unocss/core';
export declare const varEmpty = " ";
export declare const displays: Rule[];
export declare const appearances: Rule[];
export declare const cursors: Rule[];
export declare const pointerEvents: Rule[];
export declare const resizes: Rule[];
export declare const userSelects: Rule[];
export declare const whitespaces: Rule[];
export declare const contentVisibility: Rule[];
export declare const contents: Rule[];
export declare const breaks: Rule[];
export declare const textOverflows: Rule[];
export declare const textTransforms: Rule[];
export declare const fontStyles: Rule[];
export declare const fontSmoothings: Rule[];
